version: '3'
services:
 db:
  image: postgres:latest
  container_name: go-ecommerce
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: ecommerce_ums
  volumes:
    - /Users/slim1/go/fastCamp/fastcamp_PostgreSQL/db